//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webatdongsan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.YeuThich = new HashSet<YeuThich>();
        }
    
        public int ProductID { get; set; }
        public string NamePro { get; set; }
        public string DecriptionPro { get; set; }
        public string Category { get; set; }
        public Nullable<int> Price { get; set; }
        public string ImagePro { get; set; }
        public Nullable<double> Area { get; set; }
        public string Address { get; set; }
        public Nullable<int> Phone { get; set; }
        public string LienHe { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
        public Nullable<int> IdNguoiDung { get; set; }
        public string ImagePro1 { get; set; }
        public string ImagePro2 { get; set; }
        public Nullable<int> WhiteList { get; set; }
        public Nullable<int> IDCate { get; set; }
    
        public virtual Category Category1 { get; set; }
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YeuThich> YeuThich { get; set; }
    }
}
